openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /items:
    get:
      summary: Get items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    Item:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
      required:
        - name
        - age
 